### ISSUE TITLE
Save User Skin not working (ST3 OSX)

### ISSUE THREAD

**Issue by antenando** [deathaxe/sublime-skins#1]
Thanks for the plugin but it is not working for me yet.

I try to `Save User Skin` but it spills me this error:

``` py
Traceback (most recent call last):
  File "skins in /Users/nando/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 187, in run
  File "skins in /Users/nando/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 53, in load_user_skins
  File "skins in /Users/nando/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 33, in load_skins
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

No file gets created.

Also if I try to `Select Skin` it only shows me the option

``` py
Monokai
Skins
```

Will be looking forward for a solution.

Best regards

**Comment by ccodewa** [comment]
Same error for me
(ST3 Build 3120 - OSX 10.11.6)

```
Traceback (most recent call last):
  File "skins in /Users/aquarius/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 187, in run
  File "skins in /Users/aquarius/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 53, in load_user_skins
  File "skins in /Users/aquarius/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 33, in load_skins
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by antenando** [comment]
@deathaxe  good job, man. many thanks indeed!

how long does it usually take for packagecontrol to mirror master updates ?
