### ISSUE TITLE
Unable to save user skin

### ISSUE THREAD

**Issue by artofvs** [deathaxe/sublime-skins#2]
edit: Some clarification. I just installed this this package because Boxy Theme using with the new version. Switching between skins that come with Boxy works great. Only problem is saving my own skins.

When I'm trying to save skin nothing happens and console log shows this error:

```
Traceback (most recent call last):
  File "skins in /Users/sergey/Library/Application Support/Sublime Text 3/Installed Packages/Skins.sublime-package", line 238, in run
  File "./python3.3/json/__init__.py", line 268, in load
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 869: ordinal not in range(128)
```

**Comment by deathaxe** [comment]
The plugin uses the default python 'json' library to open/save the "Saved skins.skins" file. Seems this does not handle unicode characters corectly by default. Will have a look on it.
